import localFont from "next/font/local";
import "./globals.css";

// Importing custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={styles.body}
      >
        {children}
      </body>
    </html>
  );
}

// Adding some inline styles for the layout
const styles = {
  body: {
    margin: 0,
    padding: 0,
    fontFamily: "var(--font-geist-sans), sans-serif",
    backgroundColor: "#f8f9fa", // Light gray background for better contrast
    color: "#333", // Dark gray text for readability
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
};
